### ISSUE TITLE
Feature Request: Show HP instead of Health Status for Observed Tokens in the small tooltip

### ISSUE THREAD

**Issue by piper93** [reonZ/pf2e-token-hud#11]
Hi, I absolutely love the tooltip! I was wondering if there could be an option for the actual HP of observed characters, such as other party member, to be visible in the small tooltip instead of the health status. So although for an NPC, the tooltip would act the way it does now and say "Perfectly Fine" on the small tooltip, hovering over an observed token would show 17/17 HP without needing to enable the full Tooltip for observed tokens.

**Comment by reonZ** [comment]
But then i would have to also show temp HP and Stamina for those who use the variant, this is not really what the version of the tooltip was supposed to be. Sorry but i don't think, at least right now that this will become a thing.
