### ISSUE TITLE
[feature request] more keyboard support?

### ISSUE THREAD

**Issue by this-gavagai** [reonZ/pf2e-token-hud#15]
This is such an awesome module. Thank you so much for making and sharing it.

One of my players has some physical disabilities, and mouse control makes the interface a bit of a challenge. Would you ever consider including more support for keyboard-based navigation? (If it'd be helpful, I can give it a shot myself and send a pull request too!)

Very specifically, I was thinking to include a few things:

1) Key binding to show the HUD application on the currently selected token (in addition to the current hover-based mechanic)
2) Key bindings to open sidebars from the main HUD
3) Keyboard navigation of sidebar items (up/down arrows)
4) Search/filtering of sidebar items, using keyboard input string

Is any of this consistent with your design vision?

**Comment by reonZ** [comment]
1. isn't in line with the module's design and i have rejected the request a few times already (not to mention it would require to review the module's core functionality)
2. would technically be possible, i will think about it
3. i don't see how this could work, items don't have focus and there is way too many interaction possible with each of them, i will say this is unlikely to ever happen
4. this is a good idea and i will probably implement it at some point

Note that i have stopped working on the v10 version of all my modules so if anything comes to light from this, it will be for the v11 version.

**Comment by reonZ** [comment]
I have implemented the filter feature on all sidebars

**Comment by this-gavagai** [comment]
Great to see the filter feature!

I appreciate that (1) is not part of your design vision. Is there any way you'd consider exposing a method that could be called by a macro or hook to trigger display? I definitely get why you want to maintain the current design. I'm just trying to think of ways to make it more accessible to people with disabilities.

**Comment by reonZ** [comment]
In the upcoming update `1.26.0` coming today, i expose the HUD object to the global, since i made a bunch of methods public, you will be able to do what you want with that.

```js
// get the first selected token found
const token = canvas.tokens.controlled[0]
// retrieve the HUD object
const hud = game.modules.get('pf2e-token-hud').api.getHud()
// set the token as the current HUD token
hud.setToken(token)
// render the HUD on screen
hud.render()
// lock the HUD until a click is made outside
hud.lock()
```
You probably gonna want to refine your macro a bit to avoid errors when no token is selected and such, you can also fine tune the different settings of the module to find the best balance for the use of this macro (quite a lot of settings have been added or changed since you opened this issue).

I hope this helps you.

**Comment by this-gavagai** [comment]
This is awesome. This helps tremendously and I can definitely do what I need for my player from here. Your work is much appreciated.
