### ISSUE TITLE
[Feature Request] Include Temp HP into Health Status Calculation

### ISSUE THREAD

**Issue by 117ksk** [reonZ/pf2e-token-hud#18]
I am loving the Health Status feature inclusion into this module (very clean). I have used Health Estimate for months but am planning on ditching it completely if not for a couple features. 

1) Temp HP is currently not included in the Health Status feature of this module (it is an option in Health Estimate).
2) Health Status changes are not currently able to be posted to chat (it is an option in Health Estimate).

I do not know if these features are something this module would like to implement but just thought I would request them as they are very useful in my opinion and would love to see them in Interactive Token Tooltip.

**Comment by joshua-igor** [comment]
To add to this request, there is one more thing that is missing for me which is a custom range for each status. On Health Estimate you can create a select at which percentage each status String will show up. Ex: 100% for "Perfectly Fine", 99% for "It's Just a Scratch" 75% for "Injured" etc...

**Comment by reonZ** [comment]
I have no interest in trying to replicate what health estimate does, this is just a single feature in the module, i made it customizable in the amount of states and what they show already, sorry.
