### ISSUE TITLE
[Feature Reqeust] Justify Elements on the Tooltip

### ISSUE THREAD

**Issue by joshua-igor** [reonZ/pf2e-token-hud#19]
I believe that the information provided on the tooltip would be much more legible at first glance if all the elements in it were justified instead of being centered, which means the elements would have a much more rigid structure similar to a table or grid.

**Comment by reonZ** [comment]
I have tried them all and it never works.

![justify](https://github.com/reonZ/pf2e-token-hud/assets/651462/2b4564e6-563a-4879-acc3-fe09e0b13d66)

**Comment by joshua-igor** [comment]
I'm glad you have tried different approaches and since you closed the Issue you probably do not want to revisit this. But, I'm leaving this here as food for thought:
I think a more organized approach would be to let the icons be on a "grid" first because the icons are what we see first. I quick way would be to left-align the left icons and center-align the right icons and then make the labels follow them, this will ensure the elements stay in a "grid" independently from the length of the labels. I made a quick mockup of it in Paint:

![image](https://github.com/reonZ/pf2e-token-hud/assets/19159042/3fb821bb-2235-4ffc-a8ee-23d7ae5bd9b1)

I believe that this is a more organized presentation but can be tricky to implement in CSS.
I hope that you give this a thought but if you don't I wouldn't mind, this module is already incredible as is. Thank you!
