### ISSUE TITLE
Feature request: Add magic tradition under or next to the spell name or type

### ISSUE THREAD

**Issue by roi007leaf** [reonZ/pf2e-token-hud#2]
Title, this would help a lot!
Love the module!!!

**Comment by reonZ** [comment]
There is no place to put it anywhere directly and i really don't want to overload the spells sidebar with tooltips showing it, i would also have loved adding the DC.
What i could do eventually is add those details in the popup window when you click on the spell image, this would not solve the "at glance" problem but at least, those infos would be available.

**Comment by roi007leaf** [comment]
Fair.

**Comment by uniwars** [comment]
maybe just add the first letter of the tradition somewhere ? before the name of the spell like "(A) Fireball" or "A Fireball" ? or below where there is the button to expand the spell
