### ISSUE TITLE
[Issue] Tooltip not showing up on a single Token

### ISSUE THREAD

**Issue by joshua-igor** [reonZ/pf2e-token-hud#20]
There is a single player token in my game that does not show the Tooltip, every other token does, including other tokens controlled by that player. A console error shows up whenever a I hover over this token and no other token has a similar behaviour.

Foundry v11.302
PF2e System v5.0.1
pf2e-token-hud v1.20

![image](https://github.com/reonZ/pf2e-token-hud/assets/19159042/ffda3e29-90db-4035-b06c-fd12115796c1)

**Comment by joshua-igor** [comment]
I discovered that the issue was because the token had a sense of "Scent" marked as "Vague", by removing this sense the tooltip started working again.

**Comment by reonZ** [comment]
yeah, it also doesn't show in the character sheet, thanks.
