### ISSUE TITLE
Using tooltip when another token is under it

### ISSUE THREAD

**Issue by uLotUu** [reonZ/pf2e-token-hud#21]
I'm using Chrome for my games. Can't find the rule here, but sometimes tooltip dissapears if another token is under it when I move my mouse there. It's not always but makes using (an otherwise superb) module a bit clunky.

**Comment by uLotUu** [comment]
https://imageup.me/images/a07a7fb8-66bc-4900-86e8-a3ae516a6960.png?v=21
I think I know where the problem is. The tooltip should "stick" to the token. If your browser tracks your mouse on the field between the token and the tooltip and there is another token it will jump to that second token. Happens if for example, you move your mouse to slow.

**Comment by reonZ** [comment]
It should not happen if you are using the latest version of the module.


https://github.com/reonZ/pf2e-token-hud/assets/651462/09ed4671-18d5-492c-8bfd-9b4b405dac4b

As you can see, even by moving very slowly

**Comment by uLotUu** [comment]
Wierd. Newest version on CHROME:

https://github.com/reonZ/pf2e-token-hud/assets/81203867/e64d84ca-4923-4602-95eb-210f368ef06e

And It's only with TOP position. Other works fine.

**Comment by reonZ** [comment]
Foundry is releasing a fix regarding tokens under dom elements still triggering the `hoverToken` hook event in the next update `11.303` so this should make it way easier for me to handle those anyways
