### ISSUE TITLE
[Feature Request] Include 'Dead' as one of the customisable strings for Health Status

### ISSUE THREAD

**Issue by pedrogrullada** [reonZ/pf2e-token-hud#31]
As of right now the 0 HP health estimate on a token will always be "Dead". I would appreciate the ability to customize this just like the rest of the strings. My two use cases being, first that I've customised my estimates to the language one of my groups plays in, and so dead feels a little out of place along the other non-english strings, and second—admittedly, the weaker reason—that even when I play with my english speaking groups, I don't necessarily want to imply death of a character when they reach 0 HP, even though it's clear to us all that's not the case, it would be nice to be able to set more accurate nomenclature.

That is all. As an avid user of many of your modules, thank you for all you do!

**Comment by reonZ** [comment]
The dead comes from the the global effect localization string, this is not something that i added myself
The localization key being `EFFECT.StatusDead`
You can see it by using `game.i18n.localize('EFFECT.StatusDead')` in the console
