### ISSUE TITLE
Feature request: make it so the tooltip does not disappear when clicking on the token it belongs to

### ISSUE THREAD

**Issue by RavenRaconteur** [reonZ/pf2e-token-hud#32]
Even with the settings enabled to have the tooltip not disappear after render or hover, it still disappears if you click on the token it belongs to. Is there a way to implement this? Thank you!

**Comment by reonZ** [comment]
No, because any interactions with the token would be obstructed by the tooltip otherwise. Why would you want the tooltip to stay visible when clicking on the token anyways ?

**Comment by RavenRaconteur** [comment]
I don't mean opening the character sheet or anything, just clicking on the token to have it selected in case I need to move it or something like that.

**Comment by reonZ** [comment]
Yeah exactly, and if you want to move it or open its HUD, you would want the tooltip to hide, there is no reason for the tooltip to stay there.
