### ISSUE TITLE
Feature Request - Add "Notes" for NPC tooltip

### ISSUE THREAD

**Issue by ditzer252** [reonZ/pf2e-token-hud#33]
I've just discovered this module and I love it. It is great for me as GM because I don't have to open monster character sheets as much anymore.   Would it be possible to add a notes button (using maybe a question mark icon - or clicking on the monster's name) that would show the notes and traits of the monster. Thanks a lot for considering.

**Comment by reonZ** [comment]
This will be added in the next update `1.35.0`, i am just waiting for a lang PR before publishing it.

**Comment by ditzer252** [comment]
Amazing!  Thank you.
