### ISSUE TITLE
Feature Request: Make Exception for Characters with Clever Improviser, Ceremony of Knowledge, etc with the "Hide Untrained Skills" Setting

### ISSUE THREAD

**Issue by GorgoPrimus** [reonZ/pf2e-token-hud#36]
I have the setting selected where untrained skills (such that you can't use them) don't show up in the tooltip list, because that just makes sense and makes the lists shorter. One of my players just took Clever Improviser which lets you use untrained skills even if you aren't trained in them. 

Could it be made so that if a character has Clever Improviser (or other feats that do this, like Ceremony of Knowledge) that specifically let you use untrained skills, the setting makes an exception for them? 

Thanks for all you've done either way!

**Comment by reonZ** [comment]
this has been added in the `1.36.0`
