### ISSUE TITLE
Does not work on PCs

### ISSUE THREAD

**Issue by zartyva** [reonZ/pf2e-token-hud#37]
Hello,
my friends an i love this addon and we would like to use it in every way.
however the tooltip only works on NPC tokens and familiars, not PCs or companions etc.
could you help us with this problem?
kind regards
![Screen 1](https://github.com/reonZ/pf2e-token-hud/assets/143943676/681739f0-d2b6-4bac-bcca-9d4a82d1474f)
![screen 2](https://github.com/reonZ/pf2e-token-hud/assets/143943676/c5943dc3-b4d1-4b10-9812-78f5c2925201)

**Comment by zartyva** [comment]
also we just discovered for the PC tokes an error message if we open the console
![image](https://github.com/reonZ/pf2e-token-hud/assets/143943676/8b85a16e-6c06-4ca4-a6b4-3834cd62f752)

**Comment by chaot3ch** [comment]
Getting an error as well when trying to use hud on PF2e release 5.4.2. To the best of my knowledge we had no issues on v 5.4.1.

Error: An error occurred while rendering HUD 163. This is not a registered game setting
[Detected 2 packages: pf2e-token-hud, system:pf2e]
    get foundry.js:3264
    getData hud.js:453
    _render foundry.js:5736
    _render hud.js:597
    render foundry.js:5693
    render hud.js:617
    <anonymous> hud.js:216
    setTimeout handler*renderWithDelay hud.js:214
    #h hud.js:194
    <anonymous> hud.js:77
    #call foundry.js:730
    callAll foundry.js:687
    _onHoverIn foundry.js:28876
    _onHoverIn foundry.js:56095
    _onHoverIn pf2e.mjs:1
    callback foundry.js:31655
    #handleMouseOver foundry.js:31763
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerMove earcut.js:128
    mapEvent earcut.js:128
    onPointerMove earcut.js:128
foundry.js:753:30
    onError foundry.js:753
    call_wrapped libWrapper-wrapper.js:507
    <anonymous> listeners.js:135
    onError#0 libWrapper-wrapper.js:187
    render foundry.js:5695
    (Async: promise callback)
    render foundry.js:5693
    render hud.js:617
    <anonymous> hud.js:216
    (Async: setTimeout handler)
    renderWithDelay hud.js:214
    #h hud.js:194
    <anonymous> hud.js:77
    #call foundry.js:730
    callAll foundry.js:687
    _onHoverIn foundry.js:28876
    _onHoverIn foundry.js:56095
    _onHoverIn pf2e.mjs:1
    callback foundry.js:31655
    #handleMouseOver foundry.js:31763
    notifyListeners earcut.js:128
    notifyTarget earcut.js:128
    propagate earcut.js:128
    dispatchEvent earcut.js:128
    mapPointerMove earcut.js:128
    mapEvent earcut.js:128
    onPointerMove earcut.js:128

**Comment by Burrowfield** [comment]
Same issue.

**Comment by DanSlage** [comment]
Disabling PF2e Workbench fixes the problem. I am going to try and revert to an earlier version of Workbench to see if I can get both to work together.

**Comment by DanSlage** [comment]
Reverting to PF2e Workbench version 5.18.1 does work but all your Workbench configuration changes will be lost.

**Comment by zartyva** [comment]
but it works for now :) thanks a lot!! I love this addon more then any other!

**Comment by reonZ** [comment]
this is fixed in the `1.36.0`
