### ISSUE TITLE
Error messages about unlinked tokens

### ISSUE THREAD

**Issue by shemetz** [reonZ/pf2e-token-hud#38]
When having this module enabled and creating/moving/hovering/changing tokens that do not represent any actor, I have dozens of error messages appear in the console.

Some examples:

```
foundry.js:753 TypeError: Error thrown in hooked function '' for hook 'canvasPan'. Cannot read properties of null (reading 'apps')
    at fe.setToken (hud.js:126:55)
    at fe.close (hud.js:548:14)
    at Object.forceClose [as fn] (hud.js:75:38)
    at #call (foundry.js:730:20)
    at Hooks.callAll (foundry.js:687:17)
    at ontick (foundry.js:26962:15)
    at #animateFrame (foundry.js:31305:21)
    at animation.fn (foundry.js:31199:55)
    at nn.emit (index.js:89:1)
    at Dt.update (index.js:89:1)
    at Dt._tick (index.js:89:1)
```

```
hud.js:126 Uncaught TypeError: Cannot read properties of null (reading 'apps')
    at fe.setToken (hud.js:126:55)
    at fe.close (hud.js:548:14)
    at hud.js:207:18
```

Seems to me like all of these are due to [this line of code](https://github.com/reonZ/pf2e-token-hud/blob/master/src/hud.js#L126), which does not allow for a token to not have an associated actor.  Please make it use `?.` or something else, to avoid spamming the console error logs (and avoid other unexpected issues).

Obviously, the module should just not do anything for such tokens - no need to have any HUD for them.

**Comment by reonZ** [comment]
could you help me go trough the situation where you have a token not representing an actor and a clear way to reproduce your error

i just created a PC, placed a token of it on the scene, then deleted the original actor, so i now have an actorless token on the scene, but hovering over it doesn't do anything, it doesn't show the tooltip, nor do i have any errors showing up

**Comment by shemetz** [comment]
Sorry, I'm not sure, it happened to me during sessions and during prep.  I'll try to see if I can get a clean way to reproduce it.

**Comment by shemetz** [comment]
Closing for now since I couldn't reproduce it.
