### ISSUE TITLE
[Feature Request] Conditional Dead or Unconscious depending on actor type

### ISSUE THREAD

**Issue by DiceKnights** [reonZ/pf2e-token-hud#49]
First of all thanks for all your hard work, as this is one of my fav modules when running PF2e. 

Perhaps this already exists and I can't figure out how to enable it (I have looked) but I'm wondering if it is possible for the health status hover to show dead on NPCs as per normal, but perhaps Dying or Unconscious for PCs as at the moment it just shows dead for everything when they hit 0 HP.  

Even an option to change that final state descriptor, then I'd just use dying for everything.

**Comment by reonZ** [comment]
The last state at 0 is the same as the system's and even foundry's, this is why i didn't offer the option to change it.

I will close this as "not planned", but may eventually revisit the idea one day.
