### ISSUE TITLE
Feature request : Possibility to hide HUD and show it when holding a key

### ISSUE THREAD

**Issue by uniwars** [reonZ/pf2e-token-hud#5]
Hi, would that be possible to have the HUD off by default and visible only when holding a key ? the majority of time the HUD is not useful, but having an easy way to make it appears when its needed would be awesome while still keeping a minimalist UI for when it's not needed.

**Comment by reonZ** [comment]
i will look into that when i have time

**Comment by ObliquityInfinity** [comment]
Yeah this is definitely needed

**Comment by uniwars** [comment]
I just thougth that adding a way to dissociate target distance and health estimation from this feature request would be great, for example having to hold a key to show the hud but keep seeing distance and health estimation even without holding the key if enabled

also being able to choose between a key to hold or a key to on/off the hud would be nice

thanks for your work, the module has already seen insane updates
