### ISSUE TITLE
the uh action button thingy stopped working

### ISSUE THREAD

**Issue by BigTurboTM** [reonZ/pf2e-token-hud#51]
I'm not really sure when it stopped, it definitely worked a month ago, these days we click the sword button and no menu appears. An error message definitely appears in the console every time it's clicked. Here's a screenshot of that error

![image](https://github.com/reonZ/pf2e-token-hud/assets/38849339/a4cccc19-f452-401c-8e99-acf049e32a64)

it crossed my mind to make it a paste that you can copy text from in case you need to do that, but I'm honestly lazy

**Comment by reonZ** [comment]
You need to update `PF2e Toolbelt`, note that updating my modules require manual install for now, due to me having released v12 version for them and foundry's updater being lazy and not letting you update if you are not using v112.
