### ISSUE TITLE
Feature Request - PF2e Toolbelt Actionable Support

### ISSUE THREAD

**Issue by 7H3LaughingMan** [reonZ/pf2e-token-hud#54]
PF2e Toolbelt has a feature called Actionable, it allows you to attach a macro to an action and when done there is now a "use" button on the character sheet under that action which triggers said macro. However, if you do this there is there is no way to use the new "use" button from the token tooltip. Would it be possible to add compatibility for this?

**Comment by reonZ** [comment]
This module is to be replaced by a new one i am working on, this is why i didn't bother adding any compatibility with the new things i added in my other modules' recent versions.
