### ISSUE TITLE
Hide Tooltip for players

### ISSUE THREAD

**Issue by Proncho** [reonZ/pf2e-token-hud#55]
I enjoy the tooltip for use as a DM, but my players dont really use it. Is there a way to hide it for them but still use it myself? I dont see such a setting.

**Comment by reonZ** [comment]
Pretty hard to believe you could not see it.

![image](https://github.com/reonZ/pf2e-token-hud/assets/651462/e938559c-4dea-496f-848c-778523946606)

**Comment by Proncho** [comment]
Holy hell im so sorry, I dont know why it never crossed my mind that each individual player couldve disabled it. Im a little fried. Also thanks for the fast response
