### ISSUE TITLE
Feature request : Visual options to the HUD

### ISSUE THREAD

**Issue by uniwars** [reonZ/pf2e-token-hud#7]
Hi, following this discussion : https://discord.com/channels/880968862240239708/938840774357970967/1114594048213274724 I open a feature request to add some options to customize the visual of the module like :

- Colorful icons
- Dark theme
- Transparency % setting to see the scene behind
- Visual indicator of what is a button, a tooltip-able thing or an editable thing

Having options to enable/disable each part of the HUD to show only the things we need; to keep the clearest HUD for the use we have of it for example disable shield if we have no shield, level, alignement,  would be nice

thanks for your already amazing work

**Comment by reonZ** [comment]
Hello to you Ravel member (i didn't have much time to play with you guys, but i am there)

We have talked about that on the module channel and i am not planning, at the very least not any time soon to do anything about the design itself, there are solutions out there to satisfy people, theme modules or css modules that will let you make it look the way you want. This doesn't mean that everything is rejected by default, i have already caved and implemented a few things in that department.

If you are interested by joining the channel, it is on the same discord as you linked: https://discord.com/channels/880968862240239708/1113543255754285178
