### ISSUE TITLE
Feature request : Option for gm to see distance

### ISSUE THREAD

**Issue by uniwars** [reonZ/pf2e-token-hud#8]
Hi, as the title says it would be nice to have an option to see the distance between selected token and hovered token even when connected as GM, I can only see it when I'm logged on my player

it would also be nice to have the same option for health estimation to show for the GM like it does for players

**Comment by reonZ** [comment]
The feature to see the distance has been available to the GM since its inception.
![image](https://github.com/reonZ/pf2e-token-hud/assets/651462/250857c8-7c4f-4fc0-9ce8-ccef1c307b44)
And as you can see, you can also see the health status now on owned token tooltip, it has been added yesterday (the setting is disabled by default though).

**Comment by uniwars** [comment]
if "hold key keybind" is enabled both information are not visible for GM unless holding the keybind for the hovered token, which add an action to see the 2 info that we may want to always see and add the rest of the tooltip with them

**Comment by uniwars** [comment]
GM (after holding key for the selected PC and hovering the other one) ![image](https://github.com/reonZ/pf2e-token-hud/assets/65986545/65bac9c6-3bae-40ac-896b-6765296cb00f)

Player view 
![image](https://github.com/reonZ/pf2e-token-hud/assets/65986545/25ba8201-067e-4ca8-b076-4055202fdf16)

the player view only show the 2 information, if the gm want to see them he has to also show the full tooltip for the hvoered token 
![image](https://github.com/reonZ/pf2e-token-hud/assets/65986545/44b38829-746e-4b6c-847d-d9c9cb7297ce)

**Comment by reonZ** [comment]
Dunno what to tell you, i just again tested on both firefox and chrome and it is working, so unless you have set the option to `disabled`, it should work.

![image](https://github.com/reonZ/pf2e-token-hud/assets/651462/e2e41e27-0045-4548-a003-c367a2b2b737)

**Comment by reonZ** [comment]
Has an added note, the module doesn't even care if you are a GM or a player, for that kind of stuff I check if you are the owner of the token and a GM is owner of everything in foundry.
