### ISSUE TITLE
Feature request : Add stealth, athletics and perception DC

### ISSUE THREAD

**Issue by uniwars** [reonZ/pf2e-token-hud#9]
Hi, as the title says these DC are useful for sneak, escape grapple and traps for example.

Having the option to click on the DC to roll associated skill would also be nice, tog et a quick way to roll perception which is often asked in game, as well as the other two.

I would also find useful to have an option to show saves DC instead of their bonuses while still keeping the option to click on them to roll the save.

Thanks again.

**Comment by reonZ** [comment]
I have added it all, it is gonna be in the next update
